### PR TITLE
Decrease the placeholder of the need's comment

### PR DESCRIPTION
**Pull request by amanjain97**
Regarding issue #206 Font size of the placeholder of the need's comment is decreased to 14px and font color is changed to #00bfa0 (as suggested by elena) . Check if it is fine .

### CODE REVIEW

**Comment by atd** [comment]
Thank you @amanjain97 Some comments:

* Note that we are not using colors directly in the sass files, but using sass variables defined in https://github.com/P2Pvalue/teem/blob/master/src/sass/colors.sass This allows us to easily change the colors of the app (and add themes in the future if required). Please add a variable there (like `$need-comment-placeholder-color`)
* We have also a mixin available, so we don't have to code all the placeholder properties. Please take a look at https://github.com/P2Pvalue/teem/blob/master/src/sass/placeholder.sass

**Comment by amanjain97** [comment]
@atd https://github.com/P2Pvalue/teem/pull/242/commits/e68358fe7a9f7290d3116b7fad2452f0749ffdc0
I think I have made appropriate changes.

**Comment by atd** [comment]
@amanjain97 good! Just one last issue. Note that `caribbean-green` color is already defined as `light-reen`

**Comment by amanjain97** [comment]
@atd I am really sorry for mistake. https://github.com/P2Pvalue/teem/pull/242/commits/9a927cec2961cfe8f8eb8a1c49f2836b1134f2b3

**Comment by amanjain97** [comment]
Also the change in placeholder.sass was necessary as it was not working for Firefox 19+. But now it is working fine in any version of Firefox.

**Comment by atd** [comment]
@amanjain97 no worries! Now it is good to merge. However, there is another commit in the same branch (please look at the top of this pull request: 	05978b6). Could you please take the commits to another branch (and ideally squashing them into only one commit) so it can be merged?

**Comment by atd** [comment]
@amanjain97 are you still willing to finish this?

**Pull request closed without merging**
