### PR TITLE
Issue#172

### PR DESCRIPTION
**Pull request by amanjain97**
@atd I have tried to solve the issue #172 . On logout , I have redirected it to "/communities" and if the user is already logged out then it will redirect the user to login page.It works fine on my machine.
Please tell if I am missing something.

### CODE REVIEW

**Comment by atd** [comment]
@amanjain97 I would rather redirect to '/' in the case we change the default landing page in the future. What do you think?

**Comment by amanjain97** [comment]
For the time being, I think it should be /communities but when the landing page is ready I will again make a change.Still your decision will be the final one.

**Comment by atd** [comment]
I would change it now so we don't have to worry about it in the future. We don't know when it will be changed and who will be around

**Comment by atd** [comment]
Please note that it will lead the user to /communities in both cases

**Comment by amanjain97** [comment]
Ok, then I will make the change to '/' and then check the test case too. Then I will make the pull request.

**Comment by atd** [comment]
Thank you @amanjain97

**Comment by amanjain97** [comment]
@atd Please check this https://github.com/P2Pvalue/teem/pull/221

**Pull request closed without merging**
